
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author affan
 */
public class home extends javax.swing.JFrame {
    public int z=0;

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
        newbuyer.setVisible(false);
        updatebuyer.setVisible(false);
        buyerdetails.setVisible(false);
        deletebuyer.setVisible(false);
        newproduct.setVisible(false);
        updateproduct.setVisible(false);
        productdetails.setVisible(false);
        deleteproduct.setVisible(false);
        billing.setVisible(false);
        logout.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menu = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        billing = new javax.swing.JButton();
        deleteproduct = new javax.swing.JButton();
        productdetails = new javax.swing.JButton();
        updateproduct = new javax.swing.JButton();
        newproduct = new javax.swing.JButton();
        deletebuyer = new javax.swing.JButton();
        buyerdetails = new javax.swing.JButton();
        updatebuyer = new javax.swing.JButton();
        newbuyer = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 30));
        setMaximumSize(new java.awt.Dimension(1435, 800));
        setMinimumSize(new java.awt.Dimension(1435, 800));
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setSize(new java.awt.Dimension(1440, 900));

        jPanel1.setBackground(new java.awt.Color(227, 234, 230));
        jPanel1.setForeground(new java.awt.Color(102, 102, 255));

        menu.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        menu.setIcon(new javax.swing.ImageIcon("/Users/affan/Desktop/BillManagementSystem/billManagementSystem/control hide and show.png")); // NOI18N
        menu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMouseClicked(evt);
            }
        });
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });

        logout.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        logout.setText("Log Out");
        logout.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                logoutComponentShown(evt);
            }
        });
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        billing.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        billing.setText("Billing");
        billing.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                billingComponentShown(evt);
            }
        });
        billing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billingActionPerformed(evt);
            }
        });

        deleteproduct.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        deleteproduct.setText("Delete Product");
        deleteproduct.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                deleteproductComponentShown(evt);
            }
        });
        deleteproduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteproductActionPerformed(evt);
            }
        });

        productdetails.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        productdetails.setText("Product Details");
        productdetails.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                productdetailsComponentShown(evt);
            }
        });
        productdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productdetailsActionPerformed(evt);
            }
        });

        updateproduct.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        updateproduct.setText("Update Product");
        updateproduct.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                updateproductComponentShown(evt);
            }
        });
        updateproduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateproductActionPerformed(evt);
            }
        });

        newproduct.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        newproduct.setText("New Product");
        newproduct.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                newproductComponentShown(evt);
            }
        });
        newproduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newproductActionPerformed(evt);
            }
        });

        deletebuyer.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        deletebuyer.setText("Delete Buyer");
        deletebuyer.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                deletebuyerComponentShown(evt);
            }
        });
        deletebuyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebuyerActionPerformed(evt);
            }
        });

        buyerdetails.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        buyerdetails.setText("Buyer Details");
        buyerdetails.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                buyerdetailsComponentShown(evt);
            }
        });
        buyerdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyerdetailsActionPerformed(evt);
            }
        });

        updatebuyer.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        updatebuyer.setText("Update Buyer");
        updatebuyer.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                updatebuyerComponentShown(evt);
            }
        });
        updatebuyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebuyerActionPerformed(evt);
            }
        });

        newbuyer.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        newbuyer.setText("New Buyer");
        newbuyer.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                newbuyerComponentShown(evt);
            }
        });
        newbuyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newbuyerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newbuyer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updatebuyer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buyerdetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deletebuyer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newproduct)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updateproduct)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(productdetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteproduct)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(billing, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buyerdetails, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updatebuyer, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newbuyer, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deletebuyer, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newproduct, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateproduct, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productdetails, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteproduct, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(billing, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(227, 240, 244));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1460, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 726, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newbuyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newbuyerActionPerformed
        // TODO add your handling code here:
        new newBuyer().setVisible(true);
        
        
    }//GEN-LAST:event_newbuyerActionPerformed

    private void deleteproductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteproductActionPerformed
        // TODO add your handling code here:
        new deleteproduct().setVisible(true);
    }//GEN-LAST:event_deleteproductActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you want to Logout ?","Select",JOptionPane.YES_NO_OPTION);
        if(a==0){
            setVisible(false);
            new login().setVisible(true);
        }
    }//GEN-LAST:event_logoutActionPerformed

    private void menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseClicked
        // TODO add your handling code here:
        if(z==0){
            try 
            
            {
                Thread.sleep(250);
                newbuyer.setVisible(true);
                
                
             
            } catch (InterruptedException ex) {
                Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
            }      
            
        } else 
        {
        newbuyer.setVisible(false);
        updatebuyer.setVisible(false);
        buyerdetails.setVisible(false);
        deletebuyer.setVisible(false);
        newproduct.setVisible(false);
        updateproduct.setVisible(false);
        productdetails.setVisible(false);
        deleteproduct.setVisible(false);
        billing.setVisible(false);
        logout.setVisible(false);
        z=0;
        }
        
    }//GEN-LAST:event_menuMouseClicked

    private void newbuyerComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_newbuyerComponentShown
        // TODO add your handling code here:
        try 
            
            {
                Thread.sleep(250);
                updatebuyer.setVisible(true);
                
                
             
            } catch (InterruptedException ex) {
                Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
            }  
    }//GEN-LAST:event_newbuyerComponentShown

    private void updatebuyerComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_updatebuyerComponentShown
        // TODO add your handling code here:
        try 
            
            {
                Thread.sleep(250);
                buyerdetails.setVisible(true);
                
                
             
            } catch (InterruptedException ex) {
                Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
            }  
        
    }//GEN-LAST:event_updatebuyerComponentShown

    private void buyerdetailsComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_buyerdetailsComponentShown
        // TODO add your handling code here:
        try 
            
            {
                Thread.sleep(250);
                deletebuyer.setVisible(true);
                
                
             
            } catch (InterruptedException ex) {
                Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
            }  
    }//GEN-LAST:event_buyerdetailsComponentShown

    private void deletebuyerComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_deletebuyerComponentShown
        // TODO add your handling code here:
        try 
            
            {
                Thread.sleep(250);
                newproduct.setVisible(true);
                
                
             
            } catch (InterruptedException ex) {
                Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
            }  
    }//GEN-LAST:event_deletebuyerComponentShown

    private void newproductComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_newproductComponentShown
        // TODO add your handling code here:
        try 
            
            {
                Thread.sleep(250);
                updateproduct.setVisible(true);
                
                
             
            } catch (InterruptedException ex) {
                Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
            }  
    }//GEN-LAST:event_newproductComponentShown

    private void updateproductComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_updateproductComponentShown
        // TODO add your handling code here:
        try 
            
            {
                Thread.sleep(250);
                productdetails.setVisible(true);
                
                
             
            } catch (InterruptedException ex) {
                Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
            }  
    }//GEN-LAST:event_updateproductComponentShown

    private void productdetailsComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_productdetailsComponentShown
        // TODO add your handling code here:
        try 
            
            {
                Thread.sleep(250);
                deleteproduct.setVisible(true);
                
                
             
            } catch (InterruptedException ex) {
                Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
            }  
    }//GEN-LAST:event_productdetailsComponentShown

    private void deleteproductComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_deleteproductComponentShown
        // TODO add your handling code here:
        try 
            
            {
                Thread.sleep(250);
                billing.setVisible(true);
                
                
             
            } catch (InterruptedException ex) {
                Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
            }  
    }//GEN-LAST:event_deleteproductComponentShown

    private void billingComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_billingComponentShown
        // TODO add your handling code here:
        try 
            
            {
                Thread.sleep(250);
                logout.setVisible(true);
               
           
                z=1;
                
                
             
            } catch (InterruptedException ex) {
                Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
            }  
    }//GEN-LAST:event_billingComponentShown

    private void logoutComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_logoutComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutComponentShown

    private void updatebuyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebuyerActionPerformed
        // TODO add your handling code here:
        new updatebuyer().setVisible(true);
    }//GEN-LAST:event_updatebuyerActionPerformed

    private void buyerdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyerdetailsActionPerformed
        // TODO add your handling code here:
        new buyerdetails().setVisible(true);
    }//GEN-LAST:event_buyerdetailsActionPerformed

    private void deletebuyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebuyerActionPerformed
        // TODO add your handling code here:
        new deletebuyer().setVisible(true);
    }//GEN-LAST:event_deletebuyerActionPerformed

    private void newproductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newproductActionPerformed
        // TODO add your handling code here:
        new newproduct().setVisible(true);
    }//GEN-LAST:event_newproductActionPerformed

    private void updateproductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateproductActionPerformed
        // TODO add your handling code here:
        new updateproduct().setVisible(true);
    }//GEN-LAST:event_updateproductActionPerformed

    private void productdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productdetailsActionPerformed
        // TODO add your handling code here:
        new productdetails().setVisible(true);
    }//GEN-LAST:event_productdetailsActionPerformed

    private void billingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billingActionPerformed
        // TODO add your handling code here:
        new billing().setVisible(true);
    }//GEN-LAST:event_billingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton billing;
    private javax.swing.JButton buyerdetails;
    private javax.swing.JButton deletebuyer;
    private javax.swing.JButton deleteproduct;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton logout;
    private javax.swing.JButton menu;
    private javax.swing.JButton newbuyer;
    private javax.swing.JButton newproduct;
    private javax.swing.JButton productdetails;
    private javax.swing.JButton updatebuyer;
    private javax.swing.JButton updateproduct;
    // End of variables declaration//GEN-END:variables
}
